# Generated by Django 5.2.17 on 2026-08-30 22:37

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0003_seed_roles'),
        ('sinpapel', '0009_alter_historicalregistrofirma_verification_result_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSolicitudConstancia',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('datos_capturados', models.JSONField(blank=True, default=dict, verbose_name='Datos capturados')),
                ('creado', models.DateTimeField(blank=True, editable=False, null=True)),
                ('actualizado', models.DateTimeField(blank=True, editable=False, null=True)),
                ('caducidad', models.DateTimeField(blank=True, null=True)),
                ('folio', models.CharField(db_index=True, editable=False, max_length=50, verbose_name='Folio')),
                ('alerta_sla', models.BooleanField(default=False, help_text='La activa el SLAEngine cuando la solicitud excede el plazo.', verbose_name='Vencida por SLA')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('autor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dependencia', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cuentas.dependencia', verbose_name='Dependencia que atiende')),
                ('estado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sinpapel.estado', verbose_name='Estado')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modificador', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'historical Solicitud de constancia',
                'verbose_name_plural': 'historical Solicitudes de constancia',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SolicitudConstancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_capturados', models.JSONField(blank=True, default=dict, verbose_name='Datos capturados')),
                ('creado', models.DateTimeField(auto_now_add=True, null=True)),
                ('actualizado', models.DateTimeField(auto_now=True, null=True)),
                ('caducidad', models.DateTimeField(blank=True, null=True)),
                ('folio', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Folio')),
                ('alerta_sla', models.BooleanField(default=False, help_text='La activa el SLAEngine cuando la solicitud excede el plazo.', verbose_name='Vencida por SLA')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_autor', to=settings.AUTH_USER_MODEL)),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_constancia', to='cuentas.dependencia', verbose_name='Dependencia que atiende')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sinpapel.estado', verbose_name='Estado')),
                ('modificador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificador', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_constancia', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud de constancia',
                'verbose_name_plural': 'Solicitudes de constancia',
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['dependencia', 'estado'], name='tramite_eje_depende_bb6b89_idx'), models.Index(fields=['solicitante', '-creado'], name='tramite_eje_solicit_45a997_idx')],
            },
        ),
    ]
