# Generated by Django 5.2.17 on 2026-08-30 22:34

import apps.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='curp',
            field=models.CharField(blank=True, help_text='Clave Única de Registro de Población, 18 caracteres.', max_length=18, validators=[apps.core.validators.validar_curp], verbose_name='CURP'),
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=20, unique=True, verbose_name='Clave')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subordinadas', to='cuentas.dependencia', verbose_name='Dependencia superior')),
            ],
            options={
                'verbose_name': 'Dependencia',
                'verbose_name_plural': 'Dependencias',
                'ordering': ['clave'],
            },
        ),
        migrations.CreateModel(
            name='Adscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Vigente desde')),
                ('hasta', models.DateTimeField(blank=True, null=True, verbose_name='Vigente hasta')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adscripciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adscripciones', to='cuentas.dependencia', verbose_name='Dependencia')),
            ],
            options={
                'verbose_name': 'Adscripción',
                'verbose_name_plural': 'Adscripciones',
                'ordering': ['-desde'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('usuario', 'dependencia'), name='cuentas_adscripcion_activa_uniq')],
            },
        ),
    ]
